// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC14tVKgroCH7cwIRR4AgtvhRaKhhWMF_Y',
    appId: '1:416712364542:web:181433e4b5721cc6f3f0af',
    messagingSenderId: '416712364542',
    projectId: 'coralmachinetest',
    authDomain: 'coralmachinetest.firebaseapp.com',
    storageBucket: 'coralmachinetest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe_w21dKJ8actdv_Hrbed9P1kKnXaQHfc',
    appId: '1:416712364542:android:26b5c7d18f2dc519f3f0af',
    messagingSenderId: '416712364542',
    projectId: 'coralmachinetest',
    storageBucket: 'coralmachinetest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnk9wxxK3EDJw_crp_PxhuvCXylK1XARY',
    appId: '1:416712364542:ios:b96e082aed99ffe5f3f0af',
    messagingSenderId: '416712364542',
    projectId: 'coralmachinetest',
    storageBucket: 'coralmachinetest.firebasestorage.app',
    iosBundleId: 'com.example.coralMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnk9wxxK3EDJw_crp_PxhuvCXylK1XARY',
    appId: '1:416712364542:ios:b96e082aed99ffe5f3f0af',
    messagingSenderId: '416712364542',
    projectId: 'coralmachinetest',
    storageBucket: 'coralmachinetest.firebasestorage.app',
    iosBundleId: 'com.example.coralMachineTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC14tVKgroCH7cwIRR4AgtvhRaKhhWMF_Y',
    appId: '1:416712364542:web:0a4c85a0f70af280f3f0af',
    messagingSenderId: '416712364542',
    projectId: 'coralmachinetest',
    authDomain: 'coralmachinetest.firebaseapp.com',
    storageBucket: 'coralmachinetest.firebasestorage.app',
  );
}
